#ifndef ANIRA_RAVE_model_CONFIG_H
#define ANIRA_RAVE_model_CONFIG_H

#include <anira/anira.h>
#include <filesystem>
#include <fstream>

// If you want to embed the model into the binary, define USE_EMBEDDED_MODEL
// and add the model to your build as binary data (JUCE's juce_add_binary_data or
// an equivalent). When embedded, at runtime the code will extract the model
// to a temp directory and return that path to the inference code.

static std::vector<anira::ModelData> getModelData()
{
#ifdef USE_EMBEDDED_MODEL
    // BinaryData symbol names are generated by JUCE's binary-data helper.
    // Expected symbols (examples): BinaryData::altoSaxV1_e02d7ebfe3_streaming_norm_ts
    namespace fs = std::filesystem;
    fs::path dir = fs::temp_directory_path() / "RaveForMIDISynthesizer_models";
    std::error_code ec;
    fs::create_directories(dir, ec);
    fs::path modelPath = dir / "altoSaxV1_e02d7ebfe3_streaming_norm.ts";

    if (!fs::exists(modelPath))
    {
        std::ofstream ofs(modelPath, std::ios::binary);
        if (ofs)
        {
            ofs.write(reinterpret_cast<const char*>(BinaryData::altoSaxV1_e02d7ebfe3_streaming_norm_ts),
                      (std::streamsize)BinaryData::altoSaxV1_e02d7ebfe3_streaming_norm_tsSize);
            ofs.close();
        }
    }

    return {{modelPath.string(), anira::InferenceBackend::CUSTOM}};
#else
    return {{RAVE_MODEL_DIR + std::string("altoSaxV1_e02d7ebfe3_streaming_norm.ts"), anira::InferenceBackend::CUSTOM}};
#endif
}

static std::vector<anira::TensorShape> tensorShape = {
    {{{1, 1, 2048}}, {{1, 1, 2048}}, anira::InferenceBackend::CUSTOM},
};

static anira::ProcessingSpec processingSpec{
    {1}, // preprocess_input_channels
    {1},  // postprocess_output_channels
    {2048}, // preprocess_input_size
    {2048}, // postprocess_output_size
    {2048}  // internal_model_latency
};

static anira::InferenceConfig rave_model_config(
    getModelData(),
    tensorShape,
    processingSpec,
    200.00f,
    5, // number of warm up inferences (There is a risk of a loud noise playing the moment the app launches.)
    false // session_exclusive_processor because of cached convolution layers in the model
);

#endif //ANIRA_RAVE_model_CONFIG_H
